# This is a basic workflow that is manually triggered

name: Manual website deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    environment: website-prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0 
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.124.1'
        extended: true
    - name: Build public
      run: hugo
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-west-2
    - name: "Deploy written content"
      run: 'aws s3 cp public s3://codinginthetrenches.com/ --recursive --exclude "*" --include "*.html" --include "*.xml" --content-language "en" --cache-control "max-age=3600"'
    - name: "Deploy static content"
      run: 'aws s3 cp public s3://codinginthetrenches.com/ --recursive --exclude "*.html" --exclude "*.xml" --cache-control "max-age=43000"'
